spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: "[dhqclwoa12]"
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: secret-dsdfsd-f-sd-f-ds-f-ds-fsdfd-fs-df-d-f-sd-f-dsdsfsdf-ds-dsakey